include:
  - project: 'article714/build-tools'
    ref: master
    file: 'ci/python-job-templates.yml'
  - project: 'article714/build-tools'
    ref: master
    file: 'ci/docker-job-templates.yml'

stages:
  - quality
  - build
  - test
  - security
  - publish

variables:
  IMAGE_NAME: 'resty-container'

#-----------------------------------------
build_image:
  extends: .build_image
  variables:
    DOCKER_ADDTL_PARAMS: ''

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  extends: .test_image
  script:
    - runsvdir -P $SVDIR &
    - sleep 5
    - curl -v http://resty-srv:8080/

#-----------------------------------------
publish_release:
  extends: .publish_image
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG

publish_latest:
  extends: .publish_image
  variables:
    IMAGE_TAG: 'latest'
  only:
    refs:
      - production
